#!/bin/bash
# -----------------------------------------------------------------------------
#          FILE:  pre-commit
#   DESCRIPTION:  Git pre-commit hook
#        AUTHOR:  Rahul Thakur < rahulthakur.me | r@rahulthakur.me >
#       VERSION:  1.0.0
# -----------------------------------------------------------------------------


# whitespace error check
exec git diff-index --check --cached $against --


# add unwanted symLinks to gitignore
for f in $(git status --porcelain | grep '^??' | sed 's/^?? //'); do
    test -L "$f" && echo $f >> .gitignore
    test -d "$f" && echo $f\* >> .gitignore
dones
